version: "3.3"

services:
  database:
    container_name: blog-django
    image: postgres
    restart: always
    volumes:
    - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=blog
      - POSTGRES_USER=blog
    ports:
      - 5432:5432